# Generated by Django 3.1.4 on 2022-08-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
